### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by necolas** [suitcss/suit#107]
I'm interested in adding collaborators to the project. People who have used it in their apps, and helped others, fixed bugs, etc. cc @simonsmith @giuseppeg

**Comment by timkelty** [comment]
I'd love to help out.

**Comment by oleersoy** [comment]
Same here

**Comment by florianbouvot** [comment]
I'm interested too. 
I usually work with SUITCSS or INUITCSS...

**Comment by giuseppeg** [comment]
@necolas count on me :) Afaik people at Stripe and Segment use SUIT too

**Comment by necolas** [comment]
Thanks! I've added @timkelty @giuseppeg so far.

@florianbouvot and @oleersoy thanks for your offers of help, Tim and Giuseppe should be able to help review and merge any patches you contribute. We can add you as collaborators once a few patches have been merged.

**Comment by simonsmith** [comment]
I'm still using SUIT and watching the main repo, count me in

**Comment by necolas** [comment]
Great! Please all of you feel free to address issues (which you've all been doing anyway, thanks :)), manage pull requests, make changes together.

**Comment by oleersoy** [comment]
Cool - I was a little worried the project was going away :)

**Comment by necolas** [comment]
Sorry about that. I've been preoccupied with a few things at Twitter and testing out React-based approaches like https://github.com/necolas/react-native-web. I should have added collaborators sooner, so thanks for still being open to contributing.

**Comment by simonsmith** [comment]
@necolas So have you migrated away from SUIT on newer projects at Twitter. Are you finding that use of React (with inline styles) is negating your need for stricter conventions around naming etc?

**Comment by necolas** [comment]
SUIT methodology is still what new projects are using (including React apps like Periscope). Not all projects are using the tooling to enforce it at the CSS level. Here are some recent projects that use SUIT now.

* [Twitter for Websites](https://dev.twitter.com/products/web)
* Twitter's internal UI component library
* Twitter Cards
* Periscope

SUIT has worked out well for them from what I've heard, especially for Cards and Twitter for Websites since Embedded Tweets needs to display Cards (which are rendered by a different service).

I'm working on a React app that doesn't need SUIT because our build step ensures that the class names are local to a component by default, and obfuscated (hashed). I'm also interested in exploring longer-term strategies that avoid direct CSS authoring, and limit the absolute size of the CSS an app depends on.

**Comment by simonsmith** [comment]
Interesting. I'd enjoy a blog post on your findings one day I'm sure.

I'm still finding that SUIT works very well on sites that want to take a component based approach but lack something like React and the tooling around it to enforce it. It's also nice to hand other devs the docs and get everyone on the same page. The [css-modules](https://github.com/css-modules/css-modules) project also seems interesting and sounds like it shares the same approach with obfuscated class names.

In terms of tasks with this project - how about moving the SUIT preprocessor to PostCSS and removing the use of Rework? My only thought against that is the fact it isn't hard to replicate with a handful of PostCSS plugins. Be good to get suggestions/opinions

**Comment by giuseppeg** [comment]
@simonsmith that's [the plan](https://github.com/suitcss/preprocessor/issues/11) I guess

**Comment by simonsmith** [comment]
Ha, okay I didn't see that :)

**Comment by necolas** [comment]
Yeah that sounds good to me

**Comment by oleersoy** [comment]
Thumbs up to the removing rework suggestion.  Relying on it can lead to subtle issues that can easily go unnoticed like this one:
https://github.com/h5bp/html5boilerplate.com/pull/134

**Comment by timkelty** [comment]
I would say refactoring suitcss/preprocessor would be a duplication of efforts, when you could just suggest users to use cssnext + suitcss-conformance.

Personally, I've never even used it, and have have always just rolled my own rework/postcss plugin config. I'm not a huge fan of plugin "packs" like cssnext, so I would also lean towards just providing which  postcss plugins were needed.

On the flip side, cssnext is the easiest way to get someone up and running...

**Comment by timkelty** [comment]
If we [deprecate the preprocessor entirely](https://github.com/suitcss/preprocessor/issues/11), we would probably need to rewrite the tests to build with postcss.

**Comment by simonsmith** [comment]
My only reasoning for it was due to all the components and utils depending on it in their relevant `npm run build` settings. We could come up with an alternative like using [postcss-cli](https://github.com/code42day/postcss-cli)

**Comment by giuseppeg** [comment]
@timkelty @simonsmith let's move this conversation to suitcss/preprocessor#11 so that people can keep track of it

**Comment by simonsmith** [comment]
:+1:
