### ISSUE TITLE
Consider separating custom property (vars) definitions for import

### ISSUE THREAD

**Issue by timkelty** [suitcss/suit#108]
Some components define their custom properties at the top of the file, e.g. https://github.com/suitcss/components-grid/blob/master/lib/grid.css#L3-L6

This can be annoying when you want to redefine those variables.
This doesn't work:
```css
:root {
  --Some-other-var: 'foo';
  --Grid-gutter-size: 30px;
  --Arrange-gutter-size: 30px;
}

@import 'suitcss-components-grid';
```

Instead you have to import first, define you vars, and rely on source order to override, which is probably not how most people would go about things naturally.

What do people think about separating the custom property definitions to their own file, so if you chose, you could import without the definitions?

**Comment by simonsmith** [comment]
I've had no problem with just including my project specific components and settings after any SUIT components (inside `theme.css` in this example) - https://github.com/simonsmith/simonsmith.io/blob/master/source/stylesheets/src/index.css

Doesn't feel counter-intuitive (at least to me) and easier than having to remember to include a load of custom property files separately.

**Comment by timkelty** [comment]
Ok, it's probably fine then.
Just caused some brief confusion here a while back so thought I would bring it up.

**Comment by timkelty** [comment]
I guess the part that felt "weird" to me was that the custom properties are pre-defined, but the custom medias aren't. But in processing it doesn't seem to matter, I think as long as the custom media is defined anywhere it will work.

**Comment by simonsmith** [comment]
Perhaps we do need a recommended setup guide, so that users don't need to discover the best way to work. It was mentioned before in #86 I think

**Comment by timkelty** [comment]
Makes sense!

**Comment by simonsmith** [comment]
Or even just a repo of examples, much like webpack does.

**Comment by timkelty** [comment]
That's my preferred approach. I don't think I would have made it though our webpack config without that repo!
