### ISSUE TITLE
Select component

### ISSUE THREAD

**Issue by AntonTrollback** [suitcss/suit#110]
I just want to let you know about this component I'm quite happy with. https://github.com/antontrollback/select

Feel free to close the issue :)

**Comment by simonsmith** [comment]
This is nice, will be sure to try it out

**Comment by timkelty** [comment]
Nice! - Speaking of that, it would be nice to have a known 3rd party components in the readme.
Perhaps also encourage devs to name packages `suitcss-components-foo`/`suitcss-utils-foo`

**Comment by AntonTrollback** [comment]
Glad that you like it!
Good idea. I went ahead and renamed it.

**Comment by oleersoy** [comment]
That's really sweet.  Thumbs up to having a 3rd party components in the README.
