### ISSUE TITLE
Before and After Visual Testing Markup

### ISSUE THREAD

**Issue by oleersoy** [suitcss/suit#114]
With test driven design we write test first, run it, it fails, then we write the code to fix it.  If the visual tests that go along with utilities and components declare 'before / after' markup (Before would render without the utility / component...when it makes sense), then it becomes easier to comprehend the utility / component.

Also 'should' tests that correspond to utility / component features / requirements would be nice.  For example the requirement 'Should hide overflow`, would have a test that shows that it 'Should hide overflow'.
If we agree we should probably throw this type of stuff in a 'developer guidelines' document, similar to:
[Gulp Developer Guidelines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md)

**Comment by timkelty** [comment]
Are you thinking something with generated browser screenshots?

**Comment by oleersoy** [comment]
Maybe...is that a good idea?  Honestly I'm not familiar with that.  

My thinking right now is pretty primitive.  Basically the failing test would be the markup without the utility or component applied.  Then the passing test would be the same markup with the utility or component applied.  

For example suppose we have a u-hideOverflow utility.  The 'before / failing' test would show container markup with a fixed height and width and content that overflows.   The 'after / passing' test would show that once the utility is applied the overflow is hidden.  Seeing these side by side helps reason about what the utility or component is doing.

**Comment by simonsmith** [comment]
Is this something we could run on CI? 

I've been using Browserstack a lot at work, but it's not free obviously and it's quite flakey. Starts moving into the world of Selenium etc and I think that's perhaps overkill for the small amount of components we have.

**Comment by oleersoy** [comment]
Some CSS concepts are tricky to understand.  For example clearfixing.  So the idea is to have markup that demonstrates what happens before the clearfix utility is applied and after.  That way tests double as concept / user documentation, in addition to visually showing that the component / utility is doing what it's supposed to do.

If the concept is straightforward or easy to google then the additional effort is probably not worth it.

**Comment by simonsmith** [comment]
Ah, I see what you mean.

I think it might be more additional effort as you say. A lot of the styles in SUIT components are fairly straightforward and the demo pages are quite useful.

It might be out of the bounds of this project to double up as a guide for CSS concepts. I think if we're using anything sufficiently complex then a link in the code comments to a tutorial or reference would cover it.

**Comment by oleersoy** [comment]
Sure.  I think it would only be useful for a handful of utilities / components ATM.  Some of them do not have any references to outside concepts explaining the use case (Although most do) and it's not obvious what the implementation is intended to do, just by looking at the test.  These may go away with flexbox, but having some guidelines in a developer guide to prevent these types of gaps wouldn't hurt.  I'll be doing this in a project that mirrors this project.  I'll send a link when it's up.  This project can then always port pieces that it deems useful.  Feel free to close.

**Comment by simonsmith** [comment]
Cool, keep us posted.
