### ISSUE TITLE
Remove support for Bower and Component

### ISSUE THREAD

**Issue by oleersoy** [suitcss/suit#116]
Will the new 3.0.0 release still support Bower and Component?

**Comment by timkelty** [comment]
It would be interesting to see how many people are using SUIT in these ways.

I've always just installed SUIT packages via NPM.

**Comment by simonsmith** [comment]
I make use of Bower for projects at work where the CSS is in another repo but it's not on npm. Makes it easy to install and update and it still works fine with postcss. I don't think we should do anything special other than carry on following semver and pushing tags

**Comment by oleersoy** [comment]
As long as there is someone actually using a package manager, I think it's fine to support it.  What about component?

**Comment by necolas** [comment]
Component is basically dead. IMO, Bower has no real future but works with git endpoints so there's no need for explicit support in the form of a `bower.json`.

**Comment by oleersoy** [comment]
@necolas can we then assume that it's ok to delete both `component.json` and `bower.json` across all the suit projects?  The less noise the better.

BTW - It would be great if the issues could stay open until we've reached a consensus / going forward action plan.

**Comment by necolas** [comment]
yeah any stray json files can be deleted

**Comment by necolas** [comment]
> It would be great if the issues could stay open until we've reached a consensus / going forward action plan.

twitter made bower, we don't use bower. this issue is resolved :). feel free to open one to delete the json files

**Comment by simonsmith** [comment]
Sounds good to me

**Comment by oleersoy** [comment]
Nice - I'll send a pull request.  Thanks.

**Comment by oleersoy** [comment]
OK - Think I got all the bower and component json files.  Let me know if I missed anything.  Thanks.

**Comment by giuseppeg** [comment]
@oleersoy thanks for the PRs! We should update `README.md` too.
@necolas should all those version bump be major?

**Comment by oleersoy** [comment]
@giuseppeg NP :).  I updated the `README.md` for the `components-button-group`.  Let me know if that looks OK and I'll do the other ones as well.

**Comment by giuseppeg** [comment]
@oleersoy cool, I am fine with dropping any reference to Bower and Component.
You may want to wait for a second opinion though.

Either way I think that we will merge those but not tag any new version (answering my own question : )

**Comment by oleersoy** [comment]
@giuseppeg sounds good - and I think your judgement on the tagging is good.  Maybe hold off on the merging until I finish the `READMEs`, because I think my PR will automatically include my `README` updates as I push.

**Comment by oleersoy** [comment]
K - I think I got all the `READMEs`

**Comment by necolas** [comment]
there's no change for npm users, so i dont think there needs to be a version change

**Comment by oleersoy** [comment]
I think it's safe to close this issue now.  @giuseppeg I'll leave it up to you, since it references all the PRs.  I'll open new ones as I come across references to component and bower.

**Comment by simonsmith** [comment]
Now I'm seeing why consolidating all the packages into one repo might help :)

**Comment by oleersoy** [comment]
Hehe - While forking all the repos, I have to admit that the same thing crossed my mind.  However I like that there are fewer files per repo to analyze, and the fact that it's easy to visually scan build, test, and runtime dependencies to get an idea of what the repo is doing.  This is also something that distinguishes SUIT from other projects.

**Comment by simonsmith** [comment]
Right, going to get all these merged then

**Comment by giuseppeg** [comment]
:ship: :it:

**Comment by simonsmith** [comment]
All done. Thanks @oleersoy!

**Comment by ismay** [comment]
I just found out that `component.json`'s been removed. Relative to something like npm component isn't *that* widely used, but [duo](https://github.com/duojs/duo) uses `component.json` as well. And it's pretty active. So that bit of support is now gone. I guess there's no chance of this being reverted?

**Comment by giuseppeg** [comment]
hi @ismay sorry about that.
I am not super familiar with `Duo` but it seems like that you should be able to consume any github repo that has an `index.js`.

**Comment by ismay** [comment]
@giuseppeg Well in the case of something like `suitcss/base` it parses `index.css` (maybe because of the `"style"` key in `package.json`), and gets stuck at the `normalize.css` import (because the import doesn't refer to the repo, but to the name).

I guess I could also make due with postcss imports, but it is a shame that this change breaks the use of suitcss with duo.

**Comment by giuseppeg** [comment]
@ismay does `Duo` parse `package.json` at all? 
My guess is that it breaks because of `require('normalize.css/normalize.css');` There is no such repo in github :) Is there a way to fix that?

**Comment by ismay** [comment]
@giuseppeg 

> @ismay does Duo parse package.json at all?

I'm not sure, the documentation I could find wasn't clear on what it does when a component.json isn't present.

From the output it looks like it's parsing `index.css` and not `index.js` because the unresolved import in the output is `@import "normalize.css";`, which is only present in `index.css`. After that it imports `@import "./lib/base.css";` just fine.

**Comment by giuseppeg** [comment]
@dominicbarnes hi! Do you have idea of what's going on? ^

**Comment by dominicbarnes** [comment]
Looks like this library has just decided to adopt npm/browserify only, so duo support is probably out of the question now.

**Comment by giuseppeg** [comment]
@dominicbarnes I see, thank you.
I am not against bringing `component.json` back if you guys want it or need it.

**Comment by simonsmith** [comment]
I think this is the only repo that has been published since the removal. I see no harm in bringing back `component.json` if people are using it either.

**Comment by ismay** [comment]
I'd really appreciate it. But I don't how many others are using it.

**Comment by simonsmith** [comment]
@ismay This has been reverted in 1.0.1 - https://github.com/suitcss/base/releases/tag/1.0.1
Sorry for any issues. We'll look at leaving `component.json` in amongst the other packages too.

**Comment by ismay** [comment]
Cool, thanks for the quick response.

> We'll look at leaving component.json in amongst the other packages too if it's still required.

That'd be great. Support for a component.json across the entire range of packages would make the modular use of suit a lot easier.

**Comment by ismay** [comment]
Some of the packages still have their component.json removed (like components-grid, or utils, which I use as well). Is that a WIP, or will some packages have a component.json and some won't? To me it would make the most sense to either have it for all packages, or none (with my personal preference being for all of course).

**Comment by simonsmith** [comment]
Does Duo have plans to use something else, seeing as Component itself is now deprecated?

**Comment by simonsmith** [comment]
Additionally we're planning to move all the components and utils into a single repository. Could this break things further?

**Comment by ismay** [comment]
> Does Duo have plans to use something else, seeing as Component itself is now deprecated? 

I'm not sure, @dominicbarnes ?

**Comment by dominicbarnes** [comment]
Duo has no plans to adopt the `package.json` at this time. There hasn't been a whole lot of forward momentum on Duo lately, and I've honestly got no idea how large the community is that is actively using the tool.

Not having a `component.json` means Duo cannot resolve dependency versions, so it will always use `*`, which is very brittle. (and arguably unusable in any sort of production setting)

Putting everything into a single repository will certainly be awkward for Duo, but I think it will still be _possible_ to use it under that circumstance, albeit much less clean and arguably undesirable. (but it's not a use-case I've personally encountered... so who knows?)

With all that being said, I totally understand the desire from the suit team's perspective to consolidate compatibility to reduce maintenance overhead. With Component deprecated, and not really knowing how extensive the Duo community is, I don't want to be in the position of dictating support to module authors.
