### ISSUE TITLE
Update https://suitcss.github.io/ 

### ISSUE THREAD

**Issue by oleersoy** [suitcss/suit#118]
The reference to the component dependency manager should be removed.

**Comment by oleersoy** [comment]
The introduction on the site says this:

>SUIT CSS is a reliable and testable styling methodology for component-based UI development. A collection of CSS packages and build tools are available as modules. SUIT CSS plays well with React, Ember, Angular, and other component-based approaches to UI development. 

Consider:
>SUIT CSS provides css naming and structural conventions, baseline scaffolding, utilities, components, and development tools for CSS design, extension, testing, and dependency management served up as a set of easily digestible discrete set of packages adhering to a  [module based philosophy](https://github.com/substack/browserify-handbook#module-philosophy).

**Comment by oleersoy** [comment]
The Future Facing CSS Preprocessor section needs to be updated.  Also it could be more clear  how `@import` works with `package.json`.  Reference https://github.com/suitcss/suit/issues/72.

**Comment by timkelty** [comment]
@oleersoy You're referring to using `postcss-import`?

**Comment by oleersoy** [comment]
@timkelty possibly.  When I searched for the `package.json style` attribute reference documentation, I could not find any, so I have some questions around the current support level from NPM with respect to the `style` attribute, if that is indeed the approach that is going to be used.  The question is "What is the standard way to package CSS for NPM?".

Also I think the CSS Preprocessor concept should be eliminated and replaced with `snippets` that show how to perform various css preprocessing steps atomically using Gulp or Grunt.  For example:
- `@import` inlining
- CSS variables
- etc.

This avoids reliance on things like `rework-suit`, which caused a build break in [html5boilerplate.com](https://github.com/h5bp/html5boilerplate.com) when `rework-suit` removed the autoprefixer:
https://github.com/h5bp/html5boilerplate.com/pull/135

**Comment by necolas** [comment]
Let's just point to cssnext docs on setup.

**Comment by necolas** [comment]
@simonsmith there's no gh-pages branch for that repo because github automatically knows it is a gh-page from the repo name

**Comment by simonsmith** [comment]
Oh nice tip, did not know that

**Comment by giuseppeg** [comment]
@oleersoy the `style` property in `package.json` is a `rework-npm` thing.
More details can be found on the [package page](https://www.npmjs.com/package/rework-npm).

Some [folks](http://segment.io) are still using `rework` and ideally could `import` the suitcss packages and compile them with it, so I say let's keep em – it doesn't hurt anybody.

Is the dependency resolution issue still a thing? 

Regarding the docs, I personally like the current form.
<blockquote>SUIT CSS is a reliable and testable styling methodology for component-based UI development.</blockquote>
SUIT is primarily a styling methodology :+1: 
<blockquote>A collection of CSS packages and build tools are available as modules.</blockquote>
SUIT is not a framework like Boostrap, 
there are some modules in the org but you don't have to use them :+1: 

Generally speaking suitcss.github.io is just a landing page, details can be added to the [docs](suitcss/suit/tree/master/doc).

**Comment by oleersoy** [comment]
WRT to dependency management I added a request for postcss-import to support the main attribute for CSS packages:
https://github.com/postcss/postcss-import/issues/101

This will improve the workflow slightly.  At least in my case.

I would include the net effect on project steering and user impression in the criteria for evaluating whether a description is good.  Documentation should also be cohesive and DRY.  If something is changed in one place that, then hopefully it does not need to be changed in another.
