### ISSUE TITLE
Create a More Modular SUIT Build?

### ISSUE THREAD

**Issue by oleersoy** [suitcss/suit#120]
WDYT of using Gulp for the build?  This would allow us to easily add new plugins as needed.

**Comment by simonsmith** [comment]
That feels heavy handed to me. There is a discussion on [dropping the preprocessor](https://github.com/suitcss/preprocessor/issues/11#issuecomment-144819259) and using postcss directly. I'd highly recommend that approach as it allows you to create a very flexible build and it can be used with gulp too.

**Comment by timkelty** [comment]
What @simonsmith said.
