### ISSUE TITLE
Issue Etiquette

### ISSUE THREAD

**Issue by oleersoy** [suitcss/suit#121]
So far I have had 3-4 issues closed mid discussion.  Half of them were reopened.  Contributors will feel more respected and welcomed if they are allowed to close the tickets that they opened.  Although I'm certain it is not meant as such, it comes across as very arrogant when a ticket is closed mid discussion.

**Comment by simonsmith** [comment]
I disagree.

If the issue opened shouldn't/won't be implemented for whatever reason then leaving it up to the author to close it means it will just stay open forever and create noise around proper issues that aren't discussion points/questions. There are dozens of such issues peppered over this organisation.

It sounds like a lot of those things would be ideal in a gitter chatroom instead, which postcss use quite effectively to keep the noise out of the github issues. What about using that?

**Comment by timkelty** [comment]
Gitter could be a good venue for more "discussion" stuff. Also wouldn't mind hopping on a private Slack group. Seems like there's a fairly active group of a few of us that could hash stuff out more productively in discussion than issues.

**Comment by simonsmith** [comment]
One thing in favour of Gitter is it seems to keep a history of the chats and ties in nicely with issue numbers and PRs. Slack has a chat limit and is a bit annoying with the invite only nature

**Comment by timkelty** [comment]
Ok, lets stick with gitter

**Comment by simonsmith** [comment]
https://gitter.im/suitcss/suit

**Comment by oleersoy** [comment]
To be clear, the types of issues that I'm referring to are the types were closed mid discussion.  I'm sure we would all like as many contributors as possible, and if we turn them off providing short answers and acting like the discussion is over, that's not good for the health of the project, because there are plenty of projects that follow a more polite etiquette.  If something has been sitting around for 20 days, then it's obviously not that important to the person that opened it, and it can be closed, assuming everyone agrees that it's irrelevant the project.

Also for other joining in these issues are a good serve as a good introduction as to why certain things were done a certain way.

**Comment by giuseppeg** [comment]
<blockquote>Seems like there's a fairly active group of a few of us that could hash stuff out more productively in discussion than issues.</blockquote>
+1 on the chat.

**Comment by oleersoy** [comment]
I closed this issue, as it seems we have moved to gitter.  Anyways if anyone wants it reopened let me know.  :)
