### ISSUE TITLE
Validate code style with stylelint

### ISSUE THREAD

**Issue by simonsmith** [suitcss/suit#122]
As we move to PostCSS we could consider enforcing code style with [stylelint](http://stylelint.io/#shareable-configs)

There is already a config for conforming to the SUIT style rules - https://github.com/stylelint/stylelint-config-suitcss

This could then go into the travis build along with [postcss-bem-linter](https://github.com/postcss/postcss-bem-linter)

This could address #42

**Comment by timkelty** [comment]
:+1:

**Comment by AntonTrollback** [comment]
:+1:

**Comment by simonsmith** [comment]
Also this - https://github.com/davidtheclark/stylelint-selector-bem-pattern

**Comment by simonsmith** [comment]
Currently working in [components-grid](https://github.com/suitcss/components-grid/). Will close this issue when all packages are updated

**Comment by simonsmith** [comment]
Done in latest preprocessor version - https://github.com/suitcss/preprocessor

**Comment by giuseppeg** [comment]
:+1:

**Comment by jeddy3** [comment]
> Done in latest preprocessor version

Nice :tada:

**Comment by simonsmith** [comment]
All packages are now updated
