### ISSUE TITLE
Acronym meaning

### ISSUE THREAD

**Issue by FranzSkuffka** [suitcss/suit#129]
I know, acronyms are cool and everything but it would be great to know what they actually mean.

What, exactly, does S U I T stand for? I read it somewhere, but just can't find that source anymore.
Thanks for clearing this up in front!

**Comment by simonsmith** [comment]
One for @necolas perhaps

**Comment by timkelty** [comment]
It used to say somewhere...

Styles and UI Toolkit?

**Comment by FranzSkuffka** [comment]
I am writing about this alongside other toolkits in a paper so it would be great to write it out :laughing:

**Comment by necolas** [comment]
I don't think it really means anything. Maybe it did once upon a time.

**Comment by FranzSkuffka** [comment]
ok then...

**Comment by simonsmith** [comment]
Closest I've seen to it is in a diff from long ago - https://github.com/suitcss/suit/commit/515f663c1cdd8906e6e57942f7ec77a53ae77ca2#diff-04c6e90faac2675aa89e2176d2eec7d8L1

**Comment by FranzSkuffka** [comment]
"structural CSS modules for building web UIs and custom toolkits" ?

I am pretty sure I saw it somewhere not to long ago.. Past april '15...

**Comment by timkelty** [comment]
Hah, what a mouthful!

**Comment by FranzSkuffka** [comment]
I want to write something in my latex glsdefs :full_moon_with_face: can't we just make something up?

**Comment by timkelty** [comment]
We could just say it's a weird recursive acronym like PHP: SUIT UI Toolkit?

**Comment by oleersoy** [comment]
@FranzSkuffka I attempted to clean up the documentation a while back with a more targeted description of what I thought the framework was in general.  It looked something like this:

https://github.com/superfly-css/superfly-css

**Comment by FranzSkuffka** [comment]
@oleersoy that's interesting. Who is this targeted at?

BTW i think it's funny how everyone's favorite word in the CSS world seems to be methodology. Methodologies everywhere, anytime!!! yay!

**Comment by simonsmith** [comment]
> Instead, a methodology offers the theoretical underpinning for understanding which method, set of methods, or so-called “best practices” can be applied to specific case, for example, to calculating a specific result.

https://en.wikipedia.org/wiki/Methodology

**Comment by oleersoy** [comment]
@FranzSkuffka it's targeted at me :).  I need something that is as simple as SUIT, follows the SUIT naming conventions for components, and has a set of build tasks that are as easy to increment on as the components themselves.  It also uses a global module repository to describe the 'whole' and individual repositories for tasks or components.  The overall intention is to create an eco system where both the build for each component is as standardized as the methodology used to create the component.

**Comment by FranzSkuffka** [comment]
@oleersoy Thanks for the clarifications. I will take a look at it when I got some more sleep. Looks  very solid but kind of opinionated though. For example, from what I have gathered it would be hard to  integrate something like [corysimmons/typographic](https://github.com/corysimmons/typographic) as basically every module contains either hard-coded values (list: 5px margin) or variables (a currently unsupported feature for most browsers) that require knowledge of the base module. However I feel like  when one starts creating something, the first line of code is opinionated already :) Is this for twitter?

I am wondering, what is the purpose of a granularity as small as 1 module per repo? Doesn't the gulp  task take care of overhead?

@simonsmith

> A **methodology does not set out to provide solutions** - it is, therefore, **not the same as a method**. Instead, a methodology offers the theoretical underpinning for understanding which method, set of methods, or so-called “best practices” can be applied to specific case, for example, to calculating a specific result.

there was quite some part missing

> Methodology does not define specific methods

Whereas every CSS "methodology" I have come across is quite specific, SUIT as well. A methodology seemed to be more of a process model / strategy to me. However I do not mean to be nitpicking here, but probably am. Just trying to wrap my mind around how all these techniques and methods as well as the terminology relate to each other as I need to write about this. Thank you for participating in this discussion.

**Comment by oleersoy** [comment]
@FranzSkuffka personally I have no problem with something being opinionated as long as the opinions are good for the community.  For example Apache Maven gives all java developers a single standard directory structure to work with.  Before that everyone had their own directory structure with their own ant build.  Hence just about every project you looked at had a different structure and tasks had to be defined for that structure.  Once the structure is locked down, tasks become reusable.

One of the reasons why superfly is structured the way it is is to make sure that it is as simple as possible to demonstrate integration of anything with anything.  It does this by locking down as much as possible that does not restrict design freedom.  If it can be made any simpler, I'll gladly accept the idea.

I think it would be rude to discuss superfly-css further here, as this is SUIT's repository.  I only mentioned the description, as I submitted a pull request to SUITs documentation earlier, and figured that's what you were referencing.

Feel free to ask in an issue on any of the repositories.
