### ISSUE TITLE
Add issue and pull request templates

### ISSUE THREAD

**Issue by giuseppeg** [suitcss/suit#130]
GitHub introduced issue and pull request templates and it could be a good idea to include them in SUITCSS' repos
https://github.com/blog/2111-issue-and-pull-request-templates

I would put them in the `.github/` folder and try to see if symlinks work, if the do we could use a shared one which we'd host in this repo.

**Comment by simonsmith** [comment]
Sounds sensible, although not sure how symlinks would work? Perhaps one for a submodule?

**Comment by giuseppeg** [comment]
Yeah, I don't know why I said symlinks :)
Should we create a new repo `.github` ?

**Comment by simonsmith** [comment]
Yeah, I wonder if GitHub let's you have repos with a dot at the start? If not we can call it `templates` or something and just give it the `.github` name when we set up the submodule.

From reading the docs we can also include a `CONTRIBUTING.md`, but not sure how useful that is

**Comment by giuseppeg** [comment]
Yeah we can call it `github`.
To me it is useful to include a `CONTRIBUTING.md` I always read those.

**Comment by simonsmith** [comment]
Okay cool, then I think it's worth adding!

**Comment by giuseppeg** [comment]
Can you create the repo? I don't think I have the power to do that :)

**Comment by simonsmith** [comment]
https://github.com/suitcss/github It lives

**Comment by giuseppeg** [comment]
Closing because it is not possible to use `submodules` to do this.
