### ISSUE TITLE
how can i minify classname with postcss or webpack

### ISSUE THREAD

**Issue by yuchuanxi** [suitcss/suit#136]
when i use SUIT, the className become long,
and i wan't to minify the className in production

like:
**before minify**
```
// style.css
.Excerpt-thumbnail {
....
}
// index.html
<div class="Excerpt-thumbnail"></div>
```
**after minify**
```
// style.css
.a {
....
}
// index.html
<div class="a"></div>
```

**Comment by timkelty** [comment]
You may be able to use [css-loader / local scope](https://github.com/webpack/css-loader#local-scope) to achieve this. You'd still need something to sort through your templates and change class names, however.

In general, I think you will find using gzip to serve these resources will be more than enough to compensate for the extra characters in a production environment.

**Comment by yuchuanxi** [comment]
@timkelty thanks

**Comment by vreshch** [comment]
You can try to look over this 
https://github.com/vreshch/optimize-css-classnames-plugin
