### ISSUE TITLE
Utilities and naming convention

### ISSUE THREAD

**Issue by rickypaun** [suitcss/suit#137]
Why utilities classes need to be prefixed with `u-`?
Descendent elements and modifiers use camelCase, but they always are linked with a component and you should never write a class just `.className`.
Utilities could be written just `.utilityName`, couldn't it?

Maybe I'm loosing something :confused:

**Comment by giuseppeg** [comment]
hi @rickypaun the `u-` prefix makes it easier to recognise an utility when looking at some code.
Also single word utilities may conflict with namespaces or classnames that don't follow the suit convention e.g.:

```css
.something {} /* is this an utility class or some legacy name? */
.something-Component {} /* namespace */
```

Related https://github.com/suitcss/suit/issues/80#issuecomment-46094932

**Comment by Frikki** [comment]
[BEMIT: Taking the BEM Naming Convention a Step Further](http://csswizardry.com/2015/08/bemit-taking-the-bem-naming-convention-a-step-further/)
