### ISSUE TITLE
Is there a .jsbeautifyrc file for Suit CSS?

### ISSUE THREAD

**Issue by Ollie-w** [suitcss/suit#138]
Is there a .jsbeautifyrc file for Suit CSS that reflects suit CSS conventions? Beautify is a popular plugin so it could be pretty useful for people.

**Comment by simonsmith** [comment]
SUIT uses stylelint for linting and you can find the config here - https://github.com/suitcss/stylelint-config-suitcss

**Comment by Ollie-w** [comment]
With a linter I have to make any changes when I go wrong myself. Beautify just makes the changes automatically. I'm going to try using stylefmt which formats code according to whatever is specified by my stylelint configuration, but it's a lot less popular than the other beautify plugins.

**Comment by simonsmith** [comment]
I'm a little confused here, how could jsbeautify be used for CSS? Stylelint has become the standard for CSS linting.

**Comment by Ollie-w** [comment]
I'm not talking about a JS beautifier and I already use Stylelint. Many text editors have plugins that can format CSS to user-specified configurations, rather than just displaying a message saying that something hasn't followed the guidelines. The same as jsbeautify but for CSS.

**Comment by simonsmith** [comment]
Your question was specifically:

> Is there a .jsbeautifyrc file for Suit CSS that reflects suit CSS conventions? 

Maybe I mis-understood but it sounded like you're asking if we support JSBeautifier, which as its CSS we would not.

> but it's a lot less popular than the other beautify plugins.

What other more popular CSS beautify plugins are there? I only know of stylefmt as you mentioned but we don't have any plans to support other tools at this time.
