### ISSUE TITLE
What lock files we should keep?

### ISSUE THREAD

**Issue by kristoforsalmin** [suitcss/suit#147]
Hello everyone,

[Some](https://github.com/suitcss/suit) repos currently have `yarn.lock`, [others](https://github.com/suitcss/base) have `package-lock.json`. Should we keep both of them in order to support npm and Yarn at the same time?

Thanks

**Comment by timkelty** [comment]
@racse1 no, we should stick to one or the other.

**Comment by frekyll** [comment]
I noticed this as well. I think it'd be simpler to stick with `package-lock.json`—there's no reference in the docs of using Yarn to install.

**Comment by racse1** [comment]
@frekyll I agree. Even though Yarn is pretty popular, it's better to stick to the official package manager in my opinion.

**Comment by racse1** [comment]
Hi @simonsmith @giuseppeg, I'd like to hear from you guys what you think, so we're completely on the same page 😄

Again, I'd personally go with npm (it's not that slow nowadays), but nevertheless I'm looking forward to hear form you and then I'll need to prepare a few pull requests in order to close this one.

**Comment by simonsmith** [comment]
Seeing as we use `npm` in all of the scripts we should probably settle on `package-lock.json`

**Comment by giuseppeg** [comment]
is it problematic to have both?

**Comment by timkelty** [comment]
> is it problematic to have both?

I would say so. Unnecessary and confusing to the user. I agree we should stick with package-lock and consider yarn if do a big migration.

**Comment by kristoforsalmin** [comment]
Hi guys, do you think it makes sense to fix the lock files at the moment? On the one hand we're about to go monorepo where the issue will be automatically resolved, but on the other hand it might take a while, so maybe we should actually fix them anyway for the sake of consistency/maintainability. What do you think?

**Comment by simonsmith** [comment]
@racse1 Is it causing any issues at the moment?

**Comment by kristoforsalmin** [comment]
@simonsmith I don't think so 😄 Just a bit inconvenient, I guess.

I thought it'd be nice to finally close this one either by switching to `package-lock.json` everywhere or by just closing the issue as it'll be fixed with monorepo approach anyway...

**Comment by kristoforsalmin** [comment]
Closing this one as it seems to be fixed now 👍
