### ISSUE TITLE
Update naming of variables to comply with new conventions

### ISSUE THREAD

**Issue by racse1** [suitcss/suit#148]
Hello everyone,

Since we got new naming conventions for variables it's probably a good time to start applying them. Here's the list of places off the top of my head where we can potentially update stuff:

* https://github.com/suitcss/theme
* https://github.com/suitcss/components-arrange
* https://github.com/suitcss/components-grid

I might be wrong about components-arrange and components-grid, though. Documentation kindly suggests using camel case when defining shared variables, but as for component-related variables I can only guess by syntax definition and examples.

Most importantly some of the SUIT CSS users must be using those variables and if we're going to update naming I'd have considered it as a API change, therefore new major version might be required.

Thanks

**Comment by frekyll** [comment]
@racse1 I totally agree. Yeah, this could be kind of huge. I could work on a pull request for applying the new convention everywhere.

**Comment by racse1** [comment]
@frekyll Sounds great!

Few more places:

* https://github.com/suitcss/suit#quick-start
* https://github.com/suitcss/suit#example

**Comment by simonsmith** [comment]
Yeah, this crossed my mind too. Thanks for gathering it all together @racse1
