### ISSUE TITLE
Full page examples, real-world applications?

### ISSUE THREAD

**Issue by timkelty** [suitcss/suit#28]
Examples in the docs focus on single, small components, but it would be interesting to see examples of how an entire page or set of pages would would look using SUIT. This could include common design elements such as headers/footers/navigation, and how they might be marked up with SUIT components.

Is there a list of any real-world, public-facing projects using SUIT?

**Comment by dcadenas** [comment]
I created this [Fiddle](https://jsfiddle.net/dcadenas/mmm8z5ws/) with an extracted component of a flipping div I used in a project which I think is a nice example of these ideas.

**Comment by oleersoy** [comment]
That's sweet - nice work!
