### ISSUE TITLE
Managing typography with SUIT

### ISSUE THREAD

**Issue by timkelty** [suitcss/suit#75]
I'm curious if or how others are handling reusable global typography (headings, font styles & sizing, etc.),  with SUIT.
Just thinking out loud here...
### A `.Type` component

A single component to manage global typographic styles, we'll call it `.Type`.
Its descendent nodes would be your reusable typographic elements, such as `.Type-h1`,  `.Type-h2`, `.Type-finePrint`.
### A font utility

Could contain font sizing, family...
Say, `.u-fontMd`, `.u-fontLg`, `.u-fontSerif`, etc.
### Separate components

`.Hdg1`, `.Hdg2`, `.FinePrint`
I've initially resisted this, as it seems like it would get out of hand quickly.
But maybe I'm wrong. Perhaps just grouping them by name would be enough, e.g. (`.TypeHdg1`, `.TypeFinePrint1`)?
### Remove bare element styles

Instead of styling and bare `p`, `h1-6`, `small`...elements, [make them part of a component](http://anthonyshort.me/global-typographic-styles-suck/). This perhaps could be combined with the `.Type` component idea above:

``` css
.Type p { ... }
.Type h1 { ... }
.Type h2 { ... }
.Type ul { ... }
```

I'd love to hear other people's input.

**Comment by krulik** [comment]
@timkelty I'm curious what've you ended up doing eventually?
@necolas I also think your answer is missing an important reference to grouping several typography styles together.

Perhaps it's a matter of domain semantics - it's more reasonable to define a group of typography styles as a component in a website than it is in a web "app", where these details are more "theme"-ish.
So I'm leaning towards options 1 and 3.

**Comment by timkelty** [comment]
@krulik I've been toying with a few approaches, but yes - I think option 1 is probably the best place to start.

I have been sticking with a totally reset stylesheet, with default typography applied only in context (e.g. `.Type ul`). As most things I build are CMS driving, I always just wrap "content" fields with this and seems to work out nicely.
