### ISSUE TITLE
Clearly Stated Setup Directions

### ISSUE THREAD

**Issue by grayghostvisuals** [suitcss/suit#86]
Could you explain a little deeper how you see other devs using SUIT? I think the NPM instructions are lacking (build steps, how to build files, how to pull them into a project, how to automate all this) and I'm still desiring something that explains how one would use this with bower (how to build out files, how to incorporate them into a project etc.)? Appreciate the time. :beers:

**Comment by mwelche** [comment]
@lsdafjklsd i've opted to use your ember-cli add-on in my project, and I was curious whether adding additional rework plugins only required a npm install. (ex. npm install --save-dev rework-parent)

**Comment by lsdafjklsd** [comment]
@mwelche Yes sir, here is what our `brocfile.js` looks like. Only tricky thing is some rework plugins need to be called, and others need to be just passed in. Usually the github page for the plugin will give an example on usage. Hope this helps!!

```javascript
// Additional plugins for CSS
var inherit = require('rework-inherit'),
    reworkParent = require('rework-parent'),
    color = require('rework-color-function'),
    math = require('rework-math')

app = new EmberApp({
  suitOptions: {
    reworkPlugins: [reworkParent, color, inherit(), math()]
  }
});
```

**Comment by mwelche** [comment]
@lsdafjklsd thanks! i was missing suitOptions.

**Comment by mwelche** [comment]
@lsdafjklsd would be nice if instead of spitting out an index.css file, it spit out an app.css file natively since thats what ember-cli is looking for. i set the outputFile in suitOptions to 'app.css' but it would be a nice-to-have
