### ISSUE TITLE
states on descendents

### ISSUE THREAD

**Issue by vesparny** [suitcss/suit#96]
Is there any particular convention for styling descendents?

Imagine that I need to have something like this:

```css
.List-item.is-active {
   ...
}
```
Are states allowed to style descendents or it's better to extract a Component like

```css
.ListItem.is-active {
   ...
}
```
Thanks

**Comment by simonsmith** [comment]
Typically the state would apply to the root of the component. Any reason why you wouldn't want to?

**Comment by vesparny** [comment]
Oh not at all, I'm just trying to figure out the best approach to take since I'm pretty new to SUIT.
Was just wondering when is it better to split things and create a new component.

So basically 

```html
<ul class="List">
   <li class="ListItem>...</li>
  ...
</ul>
```

is the right approach to take rather than 

```html
<ul class="List">
   <li class="List-item>...</li>
  ...
</ul>
```

Since I need to apply an active style to `<li>` elements.

Right?

**Comment by davidtheclark** [comment]
One rationale for applying the state class to each item instead of a root element is that it avoids the need for descendent selectors in the CSS, reducing specificity of the selector. You can have `.List-item.is-active` rather than `.List.is-active .List-item`.

**Comment by timkelty** [comment]
In a case like this, I would go with your first example. I'm guessing I wouldn't want a `List` and a `ListItem` component.

Using a modifier is an option as well: `List-item List-item--active`

**Comment by simonsmith** [comment]
Nice example @vesparny 

I would reserve modifiers for stylistic changes, rather than state. In the example above I would probably go with `List-item.is-active` instead of creating another component.

**Comment by vesparny** [comment]
>
Typically the state would apply to the root of the component. Any reason why you wouldn't want to?

@simonsmith so basically my specific case could be an exception if I understood well?

**Comment by simonsmith** [comment]
I would agree yeah. Be interested to see what everyone else thinks, but the alternative (which is to create more components) feels cumbersome and unnecessary.

**Comment by vesparny** [comment]
Actually my example is even more complicated.

Basically this is the structure of the component that I need to style.

```html
<ul>
  <li>
    <a>
      <div>
        <span>
        <img>
```

Since I have a lot of nesting levels, I'm struggling trying to figure out an approach that fits SUIT

**Comment by timkelty** [comment]
To me, this looks like something where perhaps the `<a>` is your component.
```
<ul class="List>
  <li class="List-item">
    <a class="LinkBlock">
      <div>
        <span>
        <img>
```

**Comment by niksy** [comment]
I think `List-item.is-active` is the way to go. If you put it on top level (`List`) it would probably mean that list is active, not that particular item. As for nested structure, I agree with @timkelty, anchor would probably be separated component.

**Comment by vesparny** [comment]
Thanks for answers
